### PR TITLE
Added unit tests for redux reducers and fixed unit test for Blank component

### PR DESCRIPTION
**Pull request by GrizliK1988**
Added unit tests for redux reducers. For that I've exported each reducer separately to be able to test them.

Also I've:
1. removed QUEUE action because it was unused
2. set SHUFFLE_PLAY to expect only array payloads, because now only arrays are passed to this action
3. Improved work with action.payload for ADD_QUEUE

### CODE REVIEW

**Comment by YajanaRao** [comment]
Wow, Thanks a lot.

**Comment by YajanaRao** [comment]
Thank you for your contribution.

**Comment by GrizliK1988** [comment]
Hi,

no problem ;)

Interesting project!

**Comment by YajanaRao** [comment]
Thank you

**Pull request merged**
